version: 2
# enable-beta-ecosystems: true
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "10:00"
    labels:
      - "github-actions"
      - "dependencies"

  # Maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "10:00"
    labels:
      - "pip"
      - "dependencies"

  # Maintain dependencies for uv
  - package-ecosystem: "uv"
    directory: "/code/backend"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "10:00"
    labels:
      - "uv"
      - "dependencies"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/code/backend"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "10:00"
    labels:
      - "docker"
      - "dependencies"

  # Maintain dependencies for Terraform
  - package-ecosystem: "terraform"
    directory: "/code/infra"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "10:00"
    labels:
      - "terraform"
      - "dependencies"
